# Generated by Django 6.0.6 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_schoolstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
